# Generated by Django 4.0 on 2022-07-21 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_rename_task_owner_task_assigner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='performers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
