# Generated by Django 4.0 on 2022-07-21 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_performers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performers',
            field=models.ManyToManyField(related_name='task_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
